In [1]:
import numpy as np

In [3]:
arr=np.array([2,7,8,5,6])

In [4]:
arr

array([2, 7, 8, 5, 6])

In [5]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
ar=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
ar

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
arr3=np.arange(0,11)

In [10]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])